services:
  mysql:
    image: mysql:8.4
    container_name: devbox-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - devbox_mysql:/var/lib/mysql
    networks:
      - devbox
    command: ["--default-authentication-plugin=mysql_native_password"]

  postgres:
    image: postgres:16
    container_name: devbox-postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - devbox_pg:/var/lib/postgresql/data
    networks:
      - devbox

  redis:
    image: redis:7
    container_name: devbox-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - devbox_redis:/data
    networks:
      - devbox

volumes:
  devbox_mysql:
    name: devbox_mysql
  devbox_pg:
    name: devbox_pg
  devbox_redis:
    name: devbox_redis

networks:
  devbox:
    external: true
    name: devbox